version: '3'

vars:
  OUTPUT_DIRECTORY: dist
  OUTPUT_FILE_NAME: homelab-routing
  OUTPUT_FILE_SUFFIX:
  APP_PACKAGE:
    sh: cat go.mod | head -n1 | cut -d\  -f2
  APP_VERSION:
    sh: git describe --tags
  APP_COMMIT_HASH:
    sh: git rev-parse --short HEAD
  APP_BUILD_TIMESTAMP:
    sh: date '+%Y-%m-%dT%H:%M:%S'

tasks:
  default:
    deps:
      - start

  clean:
    cmd: rm -rf "{{.OUTPUT_DIRECTORY}}/"
    silent: true

  build:
    vars:
      ABS: "{{.OUTPUT_DIRECTORY}}/{{.OUTPUT_FILE_NAME}}{{.OUTPUT_FILE_SUFFIX}}"
      LDFLAGS: "-X 'main.Version={{.APP_VERSION}}' -X 'main.CommitHash={{.APP_COMMIT_HASH}}' -X 'main.BuildTimestamp={{.APP_BUILD_TIMESTAMP}}'"
    sources:
      - "**/*.go"
    generates:
      - "{{.ABS}}"
    cmds:
      - |
        go build -v \
          -ldflags="-w -s {{.LDFLAGS}}" \
          -o "{{.ABS}}"
      - du -sh "{{.ABS}}"

  test:
    cmd: go test -v -cover -coverprofile=coverage.out ./...

  start:
    cmd: go run .

  pkg:debian:
    deps:
      - task: build
    sources:
      - pkg/debian/DEBIAN
      - pkg/debian/etc
      - pkg/debian/usr
    generates:
      - pkg/debian/*.deb
    cmds:
      - cp "{{.OUTPUT_DIRECTORY}}/{{.OUTPUT_FILE_NAME}}{{.OUTPUT_FILE_SUFFIX}}" pkg/debian/usr/bin
      - cd pkg/debian && docker build . -o . --build-arg "DEB_ARCH=${GOARCH}" --build-arg "DEB_VERSION={{.APP_VERSION}}"
