version: '3'

vars:
  OUTPUT_DIRECTORY: dist
  OUTPUT_FILE_NAME: routing
  OUTPUT_FILE_SUFFIX:
  APP_PACKAGE:
    sh: cat go.mod | head -n1 | cut -d\  -f2
  APP_VERSION:
    sh: git describe --tags --always --abbrev=0
  APP_COMMIT_HASH:
    sh: git rev-parse --short HEAD
  APP_BUILD_TIMESTAMP:
    sh: date '+%Y-%m-%dT%H:%M:%S'

tasks:
  default:
    deps:
      - start

  clean:
    cmd: rm -rf "{{.OUTPUT_DIRECTORY}}/"
    silent: true

  build:
    vars:
      ABS: "{{.OUTPUT_DIRECTORY}}/{{.OUTPUT_FILE_NAME}}{{.OUTPUT_FILE_SUFFIX}}"
    cmds:
      - |
        go build -v \
          -ldflags="-w -s -X '{{.APP_PACKAGE}}/main.Version={{.APP_VERSION}}' -X '{{.APP_COMMIT_HASH}}/main.CommitHash={{.APP_COMMIT_HASH}}' -X '{{.APP_BUILD_TIMESTAMP}}/main.BuildTimestamp={{.APP_BUILD_TIMESTAMP}}'" \
          -o "{{.ABS}}"
      - du -sh "{{.ABS}}"

  test:
    cmd: go test -v -cover -coverprofile=coverage.out ./...

  start:
    cmd: go run .
