# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json

entryPoints:
  web:
    address: ":1337"
  websecure:
    address: ":1338"
    http:
      tls: {}
  traefik:
    address: ":1339"

providers:
  http:
    endpoint: http://localhost:1336/traefik
  file:
    directory: /etc/traefik/config
    watch: true

api:
  dashboard: true

log:
  level: INFO

accessLog: {}

metrics:
  prometheus:
    entryPoint: traefik
